import jsPDF from "jspdf";
import type { SubjectResult } from "./gpa";
import { getDepartmentLabel } from "@/data/subjects";

const MAX_MARKS_PER_SUBJECT = 100;

interface GpaPdfOpts {
  studentName: string | null;
  department: string;
  semester: number;
  gpa: number;
  totalCredits: number;
  totalGradePoints: number;
  results: SubjectResult[];
}

export function downloadGpaPdf(opts: GpaPdfOpts) {
  const doc = new jsPDF();
  const totalObtained = opts.results.reduce((a, r) => a + r.marks, 0);
  const totalActual = opts.results.length * MAX_MARKS_PER_SUBJECT;

  // Header
  doc.setFillColor(23, 76, 76);
  doc.rect(0, 0, 210, 32, "F");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("University of Swabi", 105, 15, { align: "center" });
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Semester GPA Report", 105, 24, { align: "center" });

  // Info panel
  doc.setDrawColor(220, 220, 220);
  doc.setFillColor(248, 246, 240);
  doc.rect(10, 40, 190, 24, "F");
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  doc.text(`Department: ${getDepartmentLabel(opts.department)}`, 15, 48);
  doc.text(`Semester: ${opts.semester}`, 15, 56);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 130, 48);
  doc.text(`Name: ${opts.studentName || "Guest"}`, 130, 56);

  // Summary
  doc.setFontSize(15);
  doc.setTextColor(23, 76, 76);
  doc.setFont("helvetica", "bold");
  doc.text("GPA Summary", 105, 76, { align: "center" });
  doc.setDrawColor(200, 200, 200);
  doc.line(10, 80, 200, 80);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.text(`Semester GPA: ${opts.gpa.toFixed(2)}`, 20, 90);
  doc.text(`Total Subjects: ${opts.results.length}`, 20, 98);
  doc.text(`Total Credit Hours: ${opts.totalCredits}`, 20, 106);
  doc.text(`Total Grade Points: ${opts.totalGradePoints.toFixed(2)}`, 20, 114);
  doc.text(`Obtained Marks: ${totalObtained} / ${totalActual}`, 120, 90);
  const pct = totalActual > 0 ? (totalObtained / totalActual) * 100 : 0;
  doc.text(`Percentage: ${pct.toFixed(2)}%`, 120, 98);

  // Subject table
  doc.setFontSize(15);
  doc.setTextColor(23, 76, 76);
  doc.setFont("helvetica", "bold");
  doc.text("Subject Details", 105, 128, { align: "center" });

  doc.setFillColor(23, 76, 76);
  doc.rect(10, 134, 190, 9, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("Subject", 15, 140);
  doc.text("Credits", 100, 140);
  doc.text("Marks", 128, 140);
  doc.text("Max", 152, 140);
  doc.text("Grade Pt", 175, 140);

  let y = 150;
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  opts.results.forEach((r, idx) => {
    if (y > 268) {
      doc.addPage();
      y = 20;
    }
    if (idx % 2 === 0) {
      doc.setFillColor(248, 246, 240);
      doc.rect(10, y - 5, 190, 7, "F");
    }
    doc.setTextColor(0, 0, 0);
    doc.text(r.subjectName.slice(0, 50), 15, y);
    doc.text(String(r.creditHours), 100, y);
    doc.text(String(r.marks), 128, y);
    doc.text(String(MAX_MARKS_PER_SUBJECT), 152, y);
    if (r.gradePoint === 0) doc.setTextColor(200, 40, 40);
    else doc.setTextColor(20, 100, 60);
    doc.text(r.gradePoint.toFixed(2), 175, y);
    y += 7;
  });

  // Totals row
  if (y > 268) {
    doc.addPage();
    y = 20;
  }
  doc.setFillColor(230, 240, 236);
  doc.rect(10, y - 5, 190, 8, "F");
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Totals", 15, y);
  doc.text(String(opts.totalCredits), 100, y);
  doc.text(String(totalObtained), 128, y);
  doc.text(String(totalActual), 152, y);
  doc.text(opts.gpa.toFixed(2), 175, y);
  doc.setFont("helvetica", "normal");

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by UOS GPA Calculator", 105, 290, { align: "center" });

  doc.save(`UOS_GPA_${opts.department}_S${opts.semester}.pdf`);
}

export interface CgpaSemesterDetail {
  semester: number;
  gpa: number;
  creditHours: number;
  gradePoints: number;
  subjects: SubjectResult[];
}

interface CgpaPdfOpts {
  studentName: string | null;
  department?: string | null;
  cgpa: number;
  totalCredits: number;
  totalGradePoints: number;
  semesters: CgpaSemesterDetail[];
}

export function downloadCgpaPdf(opts: CgpaPdfOpts) {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(23, 76, 76);
  doc.rect(0, 0, 210, 32, "F");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("University of Swabi", 105, 15, { align: "center" });
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Cumulative GPA Report", 105, 24, { align: "center" });

  // Info panel
  doc.setFillColor(248, 246, 240);
  doc.rect(10, 40, 190, 24, "F");
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  doc.text(`Name: ${opts.studentName || "Guest"}`, 15, 48);
  doc.text(
    `Department: ${opts.department ? getDepartmentLabel(opts.department) : "—"}`,
    15,
    56,
  );
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 130, 48);
  doc.text(`Semesters: ${opts.semesters.length}`, 130, 56);

  // Overall totals
  const allSubjects = opts.semesters.flatMap((s) => s.subjects);
  const totalObtained = allSubjects.reduce((a, r) => a + r.marks, 0);
  const totalActual = allSubjects.length * MAX_MARKS_PER_SUBJECT;
  const pct = totalActual > 0 ? (totalObtained / totalActual) * 100 : 0;

  doc.setFontSize(15);
  doc.setTextColor(23, 76, 76);
  doc.setFont("helvetica", "bold");
  doc.text("Academic Summary", 105, 76, { align: "center" });

  const boxes = [
    { label: "CGPA", value: opts.cgpa.toFixed(2), x: 15 },
    { label: "Credits", value: String(opts.totalCredits), x: 65 },
    { label: "Obtained", value: `${totalObtained}`, x: 115 },
    { label: "Out of", value: `${totalActual}`, x: 160 },
  ];
  boxes.forEach((b) => {
    doc.setFillColor(23, 76, 76);
    doc.roundedRect(b.x, 82, 35, 20, 3, 3, "F");
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "normal");
    doc.text(b.label, b.x + 17.5, 89, { align: "center" });
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(b.value, b.x + 17.5, 98, { align: "center" });
  });
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Overall Percentage: ${pct.toFixed(2)}%   ·   Total Grade Points: ${opts.totalGradePoints.toFixed(2)}`,
    105,
    112,
    { align: "center" },
  );

  let y = 122;

  // Per-semester subject tables
  opts.semesters
    .slice()
    .sort((a, b) => a.semester - b.semester)
    .forEach((sem) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      const semObtained = sem.subjects.reduce((a, r) => a + r.marks, 0);
      const semMax = sem.subjects.length * MAX_MARKS_PER_SUBJECT;

      // Section header
      doc.setFillColor(23, 76, 76);
      doc.rect(10, y, 190, 8, "F");
      doc.setFontSize(11);
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.text(`Semester ${sem.semester}`, 15, y + 5.5);
      doc.text(
        `GPA ${sem.gpa.toFixed(2)}  ·  Credits ${sem.creditHours}  ·  Marks ${semObtained}/${semMax}`,
        195,
        y + 5.5,
        { align: "right" },
      );
      y += 12;

      // Table header
      doc.setFillColor(220, 232, 228);
      doc.rect(10, y - 5, 190, 7, "F");
      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      doc.text("Subject", 15, y);
      doc.text("Credits", 100, y);
      doc.text("Marks", 128, y);
      doc.text("Max", 152, y);
      doc.text("Grade Pt", 175, y);
      y += 6;

      doc.setFont("helvetica", "normal");
      sem.subjects.forEach((r, idx) => {
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
        if (idx % 2 === 0) {
          doc.setFillColor(248, 246, 240);
          doc.rect(10, y - 4, 190, 6, "F");
        }
        doc.setTextColor(0, 0, 0);
        doc.text(r.subjectName.slice(0, 50), 15, y);
        doc.text(String(r.creditHours), 100, y);
        doc.text(String(r.marks), 128, y);
        doc.text(String(MAX_MARKS_PER_SUBJECT), 152, y);
        if (r.gradePoint === 0) doc.setTextColor(200, 40, 40);
        else doc.setTextColor(20, 100, 60);
        doc.text(r.gradePoint.toFixed(2), 175, y);
        y += 6;
      });

      // Semester totals row
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.setFillColor(230, 240, 236);
      doc.rect(10, y - 4, 190, 7, "F");
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text("Semester Total", 15, y);
      doc.text(String(sem.creditHours), 100, y);
      doc.text(String(semObtained), 128, y);
      doc.text(String(semMax), 152, y);
      doc.text(sem.gpa.toFixed(2), 175, y);
      doc.setFont("helvetica", "normal");
      y += 12;
    });

  // Footer note
  if (y > 270) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "CGPA Formula: \u03A3(GPA \u00D7 Credits) / \u03A3(Credits)",
    15,
    y + 4,
  );
  doc.text("Generated by UOS CGPA Calculator", 105, 290, { align: "center" });

  doc.save(`UOS_CGPA_${new Date().toISOString().slice(0, 10)}.pdf`);
}
