const universityData = {
    "computer-science": [
    { subjectName: "Application of ICT", creditHours: 3 },
    { subjectName: "Programming Fundamentals", creditHours: 4 },
    { subjectName: "Functional English", creditHours: 3 },
    { subjectName: "Islamic Studies", creditHours: 2 },
    { subjectName: "Civics and Community Engagement", creditHours: 2 },
    { subjectName: "Applied physics", creditHours: 3 },
    { subjectName: "Linear Algebra", creditHours: 3 },
    { subjectName: "Technical and Business Writing", creditHours: 3 },
    { subjectName: "Ideology and Constitution of Pakistan", creditHours: 2 },
    { subjectName: "Digital Logic Design", creditHours: 3 },
    { subjectName: "Object Oriented Programming", creditHours: 4 },
    { subjectName: "Discrete Structures", creditHours: 3 },
    { subjectName: "Data Structure", creditHours: 4 },
    { subjectName: "Probability and Statistics", creditHours: 3 },
    { subjectName: "HCI & Computer Graphics", creditHours: 3 },
    { subjectName: "Principles of Management", creditHours: 2 },
    { subjectName: "Expository Writing", creditHours: 3 },
    { subjectName: "Web Technologies", creditHours: 3 },
    { subjectName: "Compiler Construction", creditHours: 3 },
    { subjectName: "Analysis of Algorithms", creditHours: 3 },
    { subjectName: "Marketing Management", creditHours: 3 },
    { subjectName: "Calculus and Analytical Geometry", creditHours: 3 },
    { subjectName: "Web Engineering", creditHours: 3 },
    { subjectName: "Pakistan Studies", creditHours: 2 },
    { subjectName: "Operating Systems", creditHours: 3 },
    { subjectName: "Software Engineering", creditHours: 3 },
    { subjectName: "Theory of Automata", creditHours: 3 },
    { subjectName: "Computer Architecture", creditHours: 3 },
    { subjectName: "Data Communication and Computer Networks", creditHours: 4 },
    { subjectName: "Computer Org. & Assembly Language", creditHours: 3 },
    { subjectName: "Database Systems", creditHours: 4 },
    { subjectName: "Artificial Intelligence", creditHours: 3 },
    { subjectName: "Advance Programming – Visual Pro", creditHours: 3 },
    { subjectName: "Mobile App Development", creditHours: 3 },
    { subjectName: "Software Testing & Quality Assurance", creditHours: 3 },
    { subjectName: "Professional Practices", creditHours: 2 },
    { subjectName: "Parallel & Distributed Computing", creditHours: 3 },
    { subjectName: "Information Security", creditHours: 3 },
    { subjectName: "Multivariable Calculus", creditHours: 3 },
    { subjectName: "Final Year Project – I", creditHours: 2 },
    { subjectName: "Numerical Analysis", creditHours: 3 },
    { subjectName: "Entrepreneurship", creditHours: 2 },
    { subjectName: "Cyber Security", creditHours: 3 },
    { subjectName: "Advance database management system", creditHours: 3 },
    { subjectName: "Final Year Project – II", creditHours: 4 }
],
    "electrical-engineering": [
        { subjectName: "Basic Electrical Engineering", creditHours: 4 },
        { subjectName: "Calculus I", creditHours: 3 },
        { subjectName: "Engineering Drawing", creditHours: 2 },
        { subjectName: "Physics", creditHours: 3 },
        { subjectName: "Islamic Studies", creditHours: 2 },
        { subjectName: "Circuit Analysis", creditHours: 4 },
        { subjectName: "Calculus II", creditHours: 3 },
        { subjectName: "Programming Fundamentals", creditHours: 3 },
        { subjectName: "Applied Physics", creditHours: 3 },
        { subjectName: "Pakistan Studies", creditHours: 2 },
        { subjectName: "Digital Electronics", creditHours: 4 },
        { subjectName: "Signals and Systems", creditHours: 3 },
        { subjectName: "Electromagnetic Theory", creditHours: 3 },
        { subjectName: "Control Systems", creditHours: 3 },
        { subjectName: "Electrical Machines", creditHours: 3 },
        // Add more subjects up to 48 for electrical engineering
    ],
    "business-administration": [
        { subjectName: "Introduction to Business", creditHours: 3 },
        { subjectName: "Principles of Management", creditHours: 3 },
        { subjectName: "Financial Accounting", creditHours: 3 },
        { subjectName: "Microeconomics", creditHours: 3 },
        { subjectName: "Business Mathematics", creditHours: 3 },
        { subjectName: "Marketing Principles", creditHours: 3 },
        { subjectName: "Organizational Behavior", creditHours: 3 },
        { subjectName: "Business Statistics", creditHours: 3 },
        { subjectName: "Macroeconomics", creditHours: 3 },
        { subjectName: "Business Communication", creditHours: 3 },
        // Add more subjects up to 48 for business administration
    ],
    "biology": [
        { subjectName: "Introduction to Biology", creditHours: 4 },
        { subjectName: "General Chemistry", creditHours: 4 },
        { subjectName: "Cell Biology", creditHours: 3 },
        { subjectName: "Ecology", creditHours: 3 },
        { subjectName: "Scientific Methods", creditHours: 2 },
        { subjectName: "Genetics", creditHours: 4 },
        { subjectName: "Microbiology", creditHours: 4 },
        { subjectName: "Biochemistry", creditHours: 4 },
        { subjectName: "Evolutionary Biology", creditHours: 3 },
        { subjectName: "Plant Physiology", creditHours: 3 },
        // Add more subjects up to 48 for biology
    ],
    "english": [
        { subjectName: "Introduction to Literature", creditHours: 3 },
        { subjectName: "Composition I", creditHours: 3 },
        { subjectName: "Linguistics", creditHours: 3 },
        { subjectName: "Poetry", creditHours: 3 },
        { subjectName: "Drama", creditHours: 3 },
        { subjectName: "Composition II", creditHours: 3 },
        { subjectName: "American Literature", creditHours: 3 },
        { subjectName: "British Literature", creditHours: 3 },
        { subjectName: "Literary Theory", creditHours: 3 },
        { subjectName: "Creative Writing", creditHours: 3 },
        // Add more subjects up to 48 for english
    ]
};